# Generated by Django 5.2.12 on 2026-04-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hviezdicky', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('vytvorene', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vytvorene_recenzie', to=settings.AUTH_USER_MODEL)),
                ('prijimatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vytvorene'],
            },
        ),
    ]
