# Generated by Django 5.2.8 on 2026-05-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recenzia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dovod', models.CharField(choices=[('podvod', 'Podvodný inzerát / Neodoslaný tovar'), ('vulgarnost', 'Vulgárne správanie'), ('spam', 'Spam / Reklama'), ('ine', 'Iný dôvod')], max_length=20)),
                ('popis', models.TextField(blank=True)),
                ('vytvorene', models.DateTimeField(auto_now_add=True)),
                ('vyriesene', models.BooleanField(default=False)),
                ('obvineny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nahlásenia', to=settings.AUTH_USER_MODEL)),
                ('zalobca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podane_hlasenia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nahlásenie',
                'verbose_name_plural': 'Nahlásenia',
            },
        ),
    ]
