# Generated by Django 5.2.8 on 2026-05-11 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('zalobca', 'obvineny')},
        ),
    ]
