# Generated by Django 5.2.8 on 2026-05-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_report_unique_together'),
        ('inzeraty', '0022_inzerat_skryte_tagy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('zalobca', 'obvineny')},
        ),
        migrations.AddField(
            model_name='report',
            name='inzerat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nahlasenia', to='inzeraty.inzerat'),
        ),
        migrations.AlterField(
            model_name='report',
            name='obvineny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nahlasenia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('zalobca', 'inzerat'), ('zalobca', 'obvineny')},
        ),
    ]
