# Generated by Django 5.2.12 on 2026-07-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_report_unique_together_report_inzerat_and_more'),
        ('inzeraty', '0027_inzerat_dovod_zamietnutia'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sprava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inzeraty.sprava'),
        ),
    ]
