# Generated by Django 5.2.12 on 2026-07-05 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_report_sprava'),
        ('inzeraty', '0027_inzerat_dovod_zamietnutia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('zalobca', 'inzerat'), ('zalobca', 'obvineny'), ('zalobca', 'sprava')},
        ),
    ]
