# Generated by Django 5.2.12 on 2026-03-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
