# Generated by Django 5.2.8 on 2026-05-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_todoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('typ', models.CharField(choices=[('navrh', 'Návrh / Vylepšenie'), ('chyba', 'Nahlásenie chyby'), ('otazka', 'Všeobecná otázka')], default='navrh', max_length=20)),
                ('predmet', models.CharField(max_length=150)),
                ('sprava', models.TextField()),
                ('stav', models.CharField(choices=[('novy', 'Nový'), ('riesi_se', 'Rieši sa'), ('vyriesene', 'Vyriešené'), ('zamietnute', 'Zamietnuté')], default='novy', max_length=20)),
                ('vytvorene', models.DateTimeField(auto_now_add=True)),
                ('poznamka_admina', models.TextField(blank=True, help_text='Tvoja interná poznámka k riešeniu.', null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket / Návrh',
                'verbose_name_plural': 'Tickety a Návrhy',
                'ordering': ['-vytvorene'],
            },
        ),
    ]
