# Generated by Django 5.2.8 on 2026-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='obrazok',
            field=models.ImageField(blank=True, null=True, upload_to='inzeraty/'),
        ),
    ]
