# Generated by Django 5.2.8 on 2026-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0002_inzerat_obrazok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='cena',
            field=models.CharField(max_length=10),
        ),
    ]
