# Generated by Django 5.2.12 on 2026-03-16 19:25

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0003_alter_inzerat_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='obrazok',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='inzeraty/'),
        ),
    ]
