# Generated by Django 5.2.12 on 2026-03-26 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0004_alter_inzerat_obrazok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konverzacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvorene', models.DateTimeField(auto_now_add=True)),
                ('inzerat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inzeraty.inzerat')),
                ('kupujuci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nakupy', to=settings.AUTH_USER_MODEL)),
                ('predajca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('inzerat', 'kupujuci', 'predajca')},
            },
        ),
        migrations.CreateModel(
            name='Sprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('poslane', models.DateTimeField(auto_now_add=True)),
                ('konverzacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spravy', to='inzeraty.konverzacia')),
                ('odosielatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
