# Generated by Django 5.2.12 on 2026-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0005_konverzacia_sprava'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprava',
            name='obrazok',
            field=models.ImageField(blank=True, null=True, upload_to='chat_fotky/'),
        ),
        migrations.AlterField(
            model_name='sprava',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
