# Generated by Django 5.2.12 on 2026-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0006_sprava_obrazok_alter_sprava_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='je_aktivny',
            field=models.BooleanField(default=True),
        ),
    ]
