# Generated by Django 5.2.12 on 2026-03-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0008_sprava_upravene'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprava',
            name='precitane',
            field=models.BooleanField(default=False),
        ),
    ]
