# Generated by Django 5.2.8 on 2026-04-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0009_sprava_precitane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategórie',
            },
        ),
        migrations.AlterField(
            model_name='inzerat',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='inzerat',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inzeraty.kategoria'),
        ),
    ]
