# Generated by Django 5.2.8 on 2026-04-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0010_kategoria_alter_inzerat_cena_inzerat_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='cena',
            field=models.CharField(max_length=50),
        ),
    ]
