# Generated by Django 5.2.8 on 2026-04-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0011_alter_inzerat_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
