# Generated by Django 5.2.8 on 2026-04-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0012_alter_inzerat_cena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Typy',
            },
        ),
        migrations.AddField(
            model_name='inzerat',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inzeraty.typ'),
        ),
    ]
