# Generated by Django 5.2.12 on 2026-04-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0013_typ_inzerat_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(default='Admin', max_length=100)),
                ('info_1', models.CharField(max_length=255, verbose_name='Email alebo info 1')),
                ('info_2', models.CharField(max_length=255, verbose_name='Telefón alebo info 2')),
            ],
            options={
                'verbose_name_plural': 'Kontakt',
            },
        ),
    ]
