# Generated by Django 5.2.12 on 2026-04-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0015_recenzia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recenzia',
        ),
    ]
