# Generated by Django 5.2.12 on 2026-04-19 18:44

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0016_delete_recenzia'),
    ]

    operations = [
        migrations.CreateModel(
            name='InzeratObrazok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazok', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='inzeraty/viac/')),
                ('inzerat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatocne_obrazky', to='inzeraty.inzerat')),
            ],
            options={
                'verbose_name_plural': 'Dodatočné obrázky',
            },
        ),
    ]
