# Generated by Django 5.2.12 on 2026-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0017_inzeratobrazok'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprava',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videa/'),
        ),
    ]
