# Generated by Django 5.2.12 on 2026-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0018_sprava_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='lokalita',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
