# Generated by Django 5.2.12 on 2026-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0019_inzerat_lokalita'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inzerat',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
