# Generated by Django 5.2.8 on 2026-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0020_inzerat_lat_inzerat_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='nazov',
            field=models.CharField(max_length=50),
        ),
    ]
