# Generated by Django 5.2.8 on 2026-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0021_alter_inzerat_nazov'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='skryte_tagy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
