# Generated by Django 5.2.12 on 2026-06-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0022_inzerat_skryte_tagy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='kontrola_zlyhala',
            field=models.BooleanField(default=False),
        ),
    ]
