# Generated by Django 5.2.12 on 2026-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0023_inzerat_kontrola_zlyhala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='typ',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
