# Generated by Django 5.2.12 on 2026-06-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0024_alter_inzerat_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inzerat',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inzeraty.typ'),
        ),
    ]
