# Generated by Django 5.2.12 on 2026-06-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0025_alter_inzerat_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='status',
            field=models.CharField(default='caka_na_kontrolu', max_length=20),
        ),
    ]
