# Generated by Django 5.2.12 on 2026-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inzeraty', '0026_inzerat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inzerat',
            name='dovod_zamietnutia',
            field=models.TextField(blank=True, null=True, verbose_name='Dôvod zamietnutia'),
        ),
    ]
